services:
  openclaw:
    image: ghcr.io/zpvel/openclaw-nas-custom:latest
    container_name: openclaw
    user: "0:0"
    network_mode: host
    restart: unless-stopped
    entrypoint: ["/usr/local/bin/print-entrypoint.sh"]
    environment:
      HOME: /home/node
      GH_CONFIG_DIR: /home/node/.openclaw/gh
      GIT_CONFIG_GLOBAL: /home/node/.openclaw/gitconfig
      NODE_ENV: production
      TZ: Asia/Shanghai
      LANG: zh_CN.UTF-8
      LANGUAGE: zh_CN:zh
      LC_ALL: zh_CN.UTF-8
      PRINTER_NAME: Epson_L6268
      PRINTER_URI: ipps://192.168.1.234:631/ipp/print
      PRINTER_PPD: /usr/share/ppd/Epson/epson-inkjet-printer-escpr/Epson-L6260_Series-epson-escpr2-en.ppd.gz
    volumes:
      - /volume1/openclaw:/home/node/.openclaw
      - /volume2/docker/openclaw/patch-qqbot-model-label.py:/usr/local/bin/patch-qqbot-model-label.py:ro
